import logging
from fastapi import APIRouter, HTTPException, Query

from models import (
    SnifferStatus, SnifferPacketsResponse, SnifferAlertsResponse
)
from services.sniffer import sniffer_service

logger = logging.getLogger("netsecai.routers.sniffer")
router = APIRouter()


@router.get("/start", response_model=SnifferStatus)
async def sniffer_start(interface: str = Query(None, description="Network interface (e.g. eth0)")):
    """
    Start the real-time packet sniffer on the specified network interface.
    Requires root/administrator privileges.
    """
    try:
        status = sniffer_service.start(interface=interface)
        return status
    except Exception as exc:
        logger.error("Failed to start sniffer: %s", exc, exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Failed to start sniffer: {exc}. Ensure you have root/admin privileges.",
        )


@router.get("/stop", response_model=SnifferStatus)
async def sniffer_stop():
    """Stop the real-time packet sniffer."""
    return sniffer_service.stop()


@router.get("/packets", response_model=SnifferPacketsResponse)
async def sniffer_packets(limit: int = Query(100, ge=1, le=500)):
    """Retrieve captured packets (most recent `limit` packets)."""
    packets, protocol_stats = sniffer_service.get_packets(limit=limit)
    status = sniffer_service.status()
    return SnifferPacketsResponse(
        packets=packets,
        total_captured=status.packet_count,
        protocol_stats=protocol_stats,
    )


@router.get("/alerts", response_model=SnifferAlertsResponse)
async def sniffer_alerts():
    """Retrieve real-time anomaly alerts generated by the sniffer."""
    alerts = sniffer_service.get_alerts()
    return SnifferAlertsResponse(alerts=alerts, total_alerts=len(alerts))


@router.get("/status", response_model=SnifferStatus)
async def sniffer_status():
    """Get current sniffer status."""
    return sniffer_service.status()


@router.get("/error")
async def sniffer_error():
    """Get sniffer error message if any."""
    error = sniffer_service.get_error()
    return {"error": error}
